// <auto-generated />
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BlogContext))]
    partial class BlogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.Categories", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Brief")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CreateDate")
                        .HasColumnType("bigint");

                    b.Property<int>("DepthInTree")
                        .HasColumnType("int");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            id = 1,
                            CategoryName = "Resaurant food",
                            CreateDate = 637894925246657391L,
                            DepthInTree = 0,
                            OrderNo = 0,
                            ParentId = 0,
                            Status = false
                        },
                        new
                        {
                            id = 2,
                            CategoryName = "Travel news ",
                            CreateDate = 637894925246657423L,
                            DepthInTree = 0,
                            OrderNo = 0,
                            ParentId = 0,
                            Status = false
                        },
                        new
                        {
                            id = 3,
                            CategoryName = "Modern technology",
                            CreateDate = 637894925246657425L,
                            DepthInTree = 0,
                            OrderNo = 0,
                            ParentId = 0,
                            Status = false
                        },
                        new
                        {
                            id = 4,
                            CategoryName = "Inspiration",
                            CreateDate = 637894925246657428L,
                            DepthInTree = 0,
                            OrderNo = 0,
                            ParentId = 0,
                            Status = false
                        },
                        new
                        {
                            id = 5,
                            CategoryName = "Health Care",
                            CreateDate = 637894925246657431L,
                            DepthInTree = 0,
                            OrderNo = 0,
                            ParentId = 0,
                            Status = false
                        });
                });

            modelBuilder.Entity("Domain.Entities.Comments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RepliedTo")
                        .HasColumnType("int");

                    b.Property<long>("SendDate")
                        .HasColumnType("bigint");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Unread")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Domain.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Content = "MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower\n                                MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower to actually sit through a self-imposed MCSE training. who has the willpower to actually",
                            OrderNo = 0,
                            Status = false,
                            Title = "Second divided from form fish beast made every of seas all gathered us saying he our"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Content = "When changing the text entered by the user, a request will be sent to the server in which we transfer the characters already printed. Then we get a response from the server with possible search query options and show them to the user.\n                                Each time the user changes the text, an event handler is called, in which a request is send to the server.\n                                To optimize the number of requests sent to the server, we use Debounce.\n                                When the text is changed by the user, using Debounce allows us to create a timer, for example for 1 second. If 1 second passes and the user has not changed the text a second time, then the event handler is called and the request will be sent to the server. If the user changes the text for the second time in 1 second, then the 1st timer is reset and a new timer is created again for 1 second.",
                            OrderNo = 0,
                            Status = false,
                            Title = "Google inks pact for new 35-storey office"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Content = "I've worked on a few noteworthy titles that people probably have heard of: Oregon Trail, Expression Blend, Visual Studio, Internet Explorer, Premiere Pro, and Photoshop.\n                            I've had lots of brushes-with-fame with noteworthy developers who I've worked at the same company, and pestered in chat and email: Herb Sutter, Raymond Chen, Scott Meyers, Alexander Stepanov, Sean Parent, Gabriel Dos Reis, Arlo Belshee, Mads Torgersen, Anders Hejlsberg, Dave Abrahams.",
                            OrderNo = 0,
                            Status = false,
                            Title = "How old are you in programming ?"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Content = " If the user resizes the browser window and we need to change the content of the site.\n                                Without optimization, the following happens. On each window resize event, the window resize event handler is called. So if the user, for example, resizes the window within 10 seconds, then 100, 200, and so on events that we need to process can happen.\n                                Throttle allows us to set a time interval, more often than which the event handler will not be called. If we specify an interval of 1 second using Throttle, then the number of execution of window resize event handlers will be 10.\n                                2) Showing the user the percentage of page scrolling. When the user scrolls the page, scroll events occur, which we need to handle. With throttle we can reduce the number of handled scroll events by setting a time interval.",
                            OrderNo = 0,
                            Status = false,
                            Title = "Side Project Sunday! Hacking on anything?"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
